### ISSUE TITLE
[BE] 서버 로깅 정책 수립 및 시스템 구축

### ISSUE THREAD

**Issue by koust6u** [woowacourse-teams/2024-coduo#43]
프로젝트 로깅 정책을 팀원들과 의논해 결정하고 기술 스택을 결정해 시스템을 구축한다.
- [X] 로깅 정책 수립
- [X] 스택 결정
- [x] 시스템 구축

**Comment by kelly6bf** [comment]
[ 결정된 로깅 시스템 구성 요소 ]

## Logback
- 역할 : Java 애플리케이션의 로깅 프레임워크로, 애플리케이션 내부에서 로그를 생성하고 다양한 형식으로 출력합니다.
- 위치: 애플리케이션 내부
- 기능: 로그 메시지를 생성하고 파일, 콘솔, 네트워크 등으로 출력

## Promtail
- 역할 : 로그 수집기로, Logback이 생성한 로그 파일을 읽고 Loki로 전송합니다.
- 위치 : 애플리케이션이 실행되는 서버 또는 노드
- 기능 : 로그 파일을 모니터링하고, 새로운 로그가 생성되면 이를 Loki로 전송

## Loki
- 역할 : 로그 집계 및 저장 시스템으로, Promtail이 전송한 로그 데이터를 중앙에서 수집하고 저장합니다.
- 위치 : 중앙 로그 서버 또는 클러스터
- 기능 : 로그 데이터를 저장하고, 검색 및 필터링을 통해 로그 분석을 지원

## Grafana

- 역할 : 시각화 도구로, Loki에 저장된 로그 데이터를 시각화하고 대시보드를 통해 모니터링을 지원합니다.
- 위치 : 중앙 서버 또는 클러스터
- 기능 : 다양한 시각화 옵션을 제공하여 로그 데이터를 그래프로 표시하고, 경고 설정을 통해 이상 징후를 알림
