### ISSUE TITLE
[ALL] 회고 페이지

### ISSUE THREAD

**Issue by dle234** [woowacourse-teams/2024-coduo#852]
## to-be
- api 네이밍 통일
 -> accessToken, answers
- textarea 글자수 
- 회고 질문 작성
### 소통, 협업 
 1. 상대방의 코드 지적을 객관적으로 받아들일 수 있었나요?
    > 특별히 받아들이기 어려웠던 피드백이 있었다면 무엇이었나요?
2. 코드나 개념을 이해하지 못했을 때 솔직하게 질문하셨나요?
> 이해하지 못한 채 넘어간 부분이 있다면 무엇이었나요?
3. 고집을 버리고 페어의 제안을 수용해본 경험이 있나요?
> 수용 후 어떤것을 배웠나요? 혹은 아쉬웠던 점은 무엇인가요?
4. 내 의견을 페어에게 효과적으로 설명하고 이해시켰나요?
> 의견 전달 과정에서 어려웠던 점은 무엇인가요?

### 성장
5. 다음 페어 프로그래밍을 위해 내가 개선해야 할 점은 무엇인가요?
> 이번 페어프로그래밍을 통해 아쉬웠던 점은 무엇이었나요?
> 더 나은 개발자가 되기 위해 어떤 부분을 개선하고 싶나요? 다음 페어 프로그래밍에서는 어떤 새로운 시도를 해보고 싶나요?
6. 페어프로그래밍을 하면서 만족한 부분이 있었나요?
> 다음 페어 프로그래밍 때도 이어나가고 싶은 부분을 적어주세요!
7. 기타
> 추가로 작성하고 싶은 게 있다면 자유롭게 작성해주세요!

**Comment by reddevilmidzy** [comment]
좋은데요오

**Comment by JiHyeonL** [comment]
페어 프로그래밍을 하면서 만족했던 부분, 다음 페어 프로그래밍 때도 이어나가고 싶은 부분에 대한 항목도 있으면 좋을 것 같아요!

**Comment by yechop** [comment]
기타 남겨놓고 싶은 말이 있으면 남길수있는 선택적인 칸이 있어도 좋겠어요
